### PR TITLE
Restore config key

### LINKED ISSUE #52: `ember-cli-storybook` config key was removed in v0.3.0
### Describe the bug

The config key for this addon was changed in https://github.com/storybookjs/ember-cli-storybook/pull/50/files#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346L11-R11,
from `ember-cli-storybook` to the name of this package (`@storybook/ember-cli-storybook`)

Instead of breaking everyone, we could reinstate the old key and print a deprecation message instead.
We'll want to update any documentation too..

### Additional context

See https://github.com/storybookjs/storybook/pull/13429#issuecomment-751645907

### PR DESCRIPTION
**Pull request by BarryThePenguin**
Restores the config key change made in #50

It does include my previous PR, but I can split up the work however needed 👍🏻 See https://github.com/storybookjs/ember-cli-storybook/commit/1fa78a243720ec6fc36f178ff8138364e3eec539

Fixes #52

### CODE REVIEW

**Comment by dbendaou** [comment]
Thanks @BarryThePenguin! 

Feels like this PR is doing a little more than just restoring the `keyconfig`, maybe you could split it in 2? I would rather keep PR doing 1 thing at the time 😊
LGTM otherwise!

**Comment by BarryThePenguin** [comment]
Sure, I'll split it up

Was finding it hard working without a linter/prettier 😅

**Comment by BarryThePenguin** [comment]
Finally got around to doing this 😅

**Review by dbendaou — APPROVED** [review]

**Comment by dbendaou** [comment]
Great! LGTM 😊

**Pull request merged**
