### PR TITLE
Set window.Ember in preview-head.html. Closes #103

### LINKED ISSUE #103: [Bug] Error: Ember is not defined (Ember v4.1.1)
Component in Storybook page is displayed with an error:

Button - Text ⋅ Storybook 2022-02-07 01-45-56

Button - Emoji ⋅ Storybook 2022-02-07 02-02-13

package.json:
```
"devDependencies": {
    "@babel/core": "^7.17.0",
    "@ember/optional-features": "^2.0.0",
    "@ember/test-helpers": "^2.6.0",
    "@glimmer/component": "^1.0.4",
    "@glimmer/tracking": "^1.0.4",
    "@storybook/addon-actions": "^6.4.18",
    "@storybook/addon-essentials": "^6.4.18",
    "@storybook/addon-links": "^6.4.18",
    "@storybook/builder-webpack5": "^6.4.18",
    "@storybook/ember": "^6.4.18",
    "@storybook/ember-cli-storybook": "^0.4.0",
    "@storybook/manager-webpack5": "^6.4.18",
    "autoprefixer": "^10.0.0",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.2.3",
    "babel-plugin-ember-modules-api-polyfill": "^3.5.0",
    "babel-plugin-htmlbars-inline-precompile": "^5.3.1",
    "broccoli-asset-rev": "^3.0.0",
    "ember-auto-import": "^2.2.4",
    "ember-cli": "~4.1.1",
    "ember-cli-app-version": "^5.0.0",
    "ember-cli-babel": "^7.26.11",
    "ember-cli-dependency-checker": "^3.2.0",
    "ember-cli-htmlbars": "^6.0.1",
    "ember-cli-inject-live-reload": "^2.1.0",
    "ember-cli-sri": "^2.1.1",
    "ember-cli-terser": "^4.0.2",
    "ember-cli-typescript": "^5.0.0",
    "ember-cli-typescript-blueprints": "^3.0.0",
    "ember-data": "~4.1.0",
    "ember-export-application-global": "^2.0.1",
    "ember-fetch": "^8.1.1",
    "ember-load-initializers": "^2.1.2",
    "ember-page-title": "^7.0.0",
    "ember-qunit": "^5.1.5",
    "ember-resolver": "^8.0.3",
    "ember-source": "~4.1.0",
    "ember-template-lint": "^4.0.0",
    "ember-welcome-page": "^6.0.0",
    "eslint": "^8.8.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-ember": "^10.5.8",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-qunit": "^7.2.0",
    "eslint-plugin-storybook": "^0.5.6",
    "html-webpack-plugin": "^5.5.0",
    "loader.js": "^4.7.0",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.6",
    "prettier": "^2.5.1",
    "qunit": "^2.17.2",
    "qunit-dom": "^2.0.0",
    "tailwindcss": "^3.0.0",
    "typescript": "^4.5.5",
    "webpack": "^5.68.0"
  },
```

### Steps to reproduce the behavior

1. `ember install @storybook/ember-cli-storybook`
2. `npx sb init`
3. `npm run storybook`
4.  See error

### Environment

 - OS: macOS Monterey 12.1
 - Node.js version: v14.17.6
 - NPM version: 8.1.2
 - Browser: Chrome 
 - Browser version: 98.0.4758.80

### PR DESCRIPTION
**Pull request by benedikt**
This is an attempt at fixing Storybook on Ember 4.1+ by explicitly setting the `Ember` global in the generated `preview-head.html`. It's working for our Storybook setup. 

It's admittedly a sledge hammer solution, but it's working until there's a proper solution. 

This should "fix" #103 as well as storybookjs/storybook#18028

### CODE REVIEW

**Comment by gossi** [comment]
I think, that's that hotfix patch we would need for the time being. 

Can you also update the `.github/workflows/ci.yml` to include the lts version, that are in `config/ember-try.js` - they have become out of sync, so the tests can go green?

**Comment by benedikt** [comment]
@gossi Updated, but it's still failing because of ember-auto-import. I'll see what I can do to get it to pass, but feels like a separate issue to me.

**Comment by gossi** [comment]
Thank you @benedikt - I'm fine with that ✅ What do @gabrielcsapo and/or @dbendaou think? I'm not sure if I missed anything really important on this one?

**Review by gossi — APPROVED** [review]

**Review by gabrielcsapo — APPROVED** [review]
Thank you for the fix!

**Comment by dbendaou** [comment]
Looks good to me, though it's not the best solution at least it allows people to use it with Ember 4! 😄
Many thanks @benedikt!!!

**Review by dbendaou — APPROVED** [review]

**Comment by va11ydation** [comment]
For the life of me I cannot connect storybook to ember 4.1+.
I'm currently working in 4.10.0. What is the optimal version of storybook it should pair with? Is there an example project of a fresh ember install paired with a fresh storybook install?

**Pull request merged**
