### PR TITLE
Makes sure that only URLs that begin with the rootURL get converted to relative paths

### LINKED ISSUE #29: preview-head.html bug when rootURL is /
When `tests/index.html` file contains CDN links and rootURL configured to be `/`, then `preview-head` generation works slightly wrong. Issue is reproducible with default `environment.js`, generated by `ember new`.

Example:
```
'use strict'

module.exports = function (environment) {
  return {
    rootURL: '/'
  }
}
```

Input `index.html` link:
```
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto&display=swap" />
```
Output `preview-head.html` link:
```
<link rel="stylesheet" href="https:.//fonts.googleapis.com/css?family=Roboto&display=swap" />
                                   ^ here is an issue
```

### PR DESCRIPTION
**Pull request by benedikt**
This fixes including additional resources (such as styles) from external servers using absolute paths. Fixes #29

### CODE REVIEW

**Comment by benedikt** [comment]
@gabrielcsapo Is there anything I can do to help get this merged (or the underlying issue to be fixed)?

**Comment by rohitpaulk** [comment]
fwiw, we've been running into the same issue.

**Comment by gabrielcsapo** [comment]
LGTM! @dbendaou thoughts on merging this?

**Review by gabrielcsapo — APPROVED** [review]

**Review by dbendaou — APPROVED** [review]

**Comment by dbendaou** [comment]
LGTM!

**Comment by gabrielcsapo** [comment]
I will look to bump this in the same minor with https://github.com/storybookjs/ember-cli-storybook/pull/57. Should be bumped by today if I can get reviews

**Comment by benedikt** [comment]
Thanks for reviewing, merging and releasing 👍

**Pull request merged**
